import { createClient } from '@supabase/supabase-js'

export const supabase = createClient('https://lygonmneehvswurgzvfg.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5Z29ubW5lZWh2c3d1cmd6dmZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODYxMjY5MDAsImV4cCI6MjAwMTcwMjkwMH0.FhvKwI63Ljt5KFTNVrZt5gD8F9eRvDxdSmBOPOm6pt4')